<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ConsultaRecibosService" targetNamespace="http://fake.com/empresa/dominio/ConsultaRecibosService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://fake.com/empresa/dominio/ConsultaRecibosService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="ConsultaRecibosServiceHttpBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>

  <wsdl:types>
    <xsd:schema targetNamespace="http://fake.com/empresa/dominio/ConsultaRecibosService">
      <xsd:include schemaLocation="v1.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="consultarRequest">
    <wsdl:part element="tns:consultar" name="consultarRequest"/>
  </wsdl:message>
  <wsdl:message name="consultarResponse">
    <wsdl:part element="tns:consultarResponse" name="consultarResponse"/>
  </wsdl:message>
  <wsdl:message name="consultarException">
    <wsdl:part element="tns:consultarException" name="consultarException"/>
  </wsdl:message>
  <wsdl:portType name="ConsultaRecibosService">
    <wsdl:operation name="consultar">
      <wsdl:input message="tns:consultarRequest" name="consultarRequest"/>
      <wsdl:output message="tns:consultarResponse" name="consultarResponse"/>
      <wsdl:fault message="tns:consultarException" name="consultarException"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="ConsultaRecibosServiceHttpBinding" type="tns:ConsultaRecibosService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultar">
      <soap:operation soapAction="http://fake.com/empresa/dominio/ConsultaRecibosService/consultar"/>
      <wsdl:input name="consultarRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultarResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="consultarException">
        <soap:fault name="consultarException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="ConsultaRecibosServiceHttpService">
    <wsdl:port binding="tns:ConsultaRecibosServiceHttpBinding" name="ConsultaRecibosServiceHttpPort">
      <soap:address location="http://fake.com/empresa/dominio/ConsultaRecibosService/v1"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
